##########
# DO NOT RENAME THIS FILE TO CONFIGURATION.YAML! YOU WILL BREAK YOUR CONFIG IF YOU DO SO!
# INSTEAD, COPY THIS CODE WITHIN YOUR OWN CONFIGURATION.YAML          
##########


sensor: !include sensors.yaml
template: !include templates.yaml

homeassistant:
  customize: !include customize.yaml
