##########
# DO NOT RENAME THIS FILE TO SENSORS.YAML! YOU WILL BREAK YOUR CONFIG IF YOU DO SO!
# INSTEAD, COPY THIS CODE WITHIN YOUR OWN SENSORS.YAML          
##########

```
#### Afvalwijzer ##################################
- platform: afvalwijzer
  provider: afvalstoffendienstkalender # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer or afvalstoffendienstkalender
  postal_code: 5241CD # (required, default = '')
  street_number: 49 # (required, default = '')
  #    suffix: A                            # (optional, default = '')
  #    exclude_pickup_today: true       # (optional, default = true) to take or not to take Today into account in the next pickup.
  default_label: Geen # (optional, default = Geen) label if no date found
#    id: ''                           # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
#    exclude_list: ''                 # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft"

```